server {
  listen 80;
  server_name _;

  charset utf-8;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_tokens off;

  # Raíz del sitio
  root /usr/share/nginx/html;
  index index.html;

  # Gzip para recursos estáticos
  gzip on;
  gzip_comp_level 5;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  # Cabeceras de seguridad básicas
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";
  add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://maps.gstatic.com; font-src 'self' https://fonts.gstatic.com; frame-src https://www.google.com; connect-src 'self';";

  # Cache estática agresiva para assets (se puede invalidar cambiando nombres)
  location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|webp)$ {
    access_log off;
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
  }

  # HTML sin cache para ver cambios al instante
  location = /index.html {
    add_header Cache-Control "no-cache";
  }

  # Raíz: entrega index
  location / {
    try_files $uri $uri/ /index.html;
  }
}
